# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Federico Barusco
title: Data Engineer
phone: +39 3462262288
email: fbarusco@gmail.com
website: www.github.com/fedebarusco

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  fedebarusco
stackoverflow_username: fedex #13314649
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: fede_barusco
linkedin_username: federicobarusco
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/Fototessera_Barusco_Federico_020219.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Federico and I'm a data engineer, I have experience making software and web apps. I have worked at a number of customer companies gaining teamwork and organizational skills.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data science and data engineering some of my other interests and hobbies are:
   - Indoor and outdoor sports (Gym, Hiking, Trekking, Cycling)
   - Cooking
   - Gardening and DIY

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
